# Generated by Django 5.2.11 on 2026-02-25 00:28

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='documents',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/hp/Desktop/hr_saas/private_media')), upload_to='employees/documents/'),
        ),
    ]
